"""them bang token ledger

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-18 14:06:54.742083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, Sequence[str], None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("task", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_ledger_created_at"), "token_ledger", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_token_ledger_provider"), "token_ledger", ["provider"], unique=False)
    op.create_index(op.f("ix_token_ledger_task"), "token_ledger", ["task"], unique=False)
    op.create_index(op.f("ix_token_ledger_user_id"), "token_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_ledger_user_id"), table_name="token_ledger")
    op.drop_index(op.f("ix_token_ledger_task"), table_name="token_ledger")
    op.drop_index(op.f("ix_token_ledger_provider"), table_name="token_ledger")
    op.drop_index(op.f("ix_token_ledger_created_at"), table_name="token_ledger")
    op.drop_table("token_ledger")
    # ### end Alembic commands ###
